# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: changelog

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
#        required: true
#        default: '2.4.0'
#      snapshotversion:
#        description: 'Next snapshot version'
#        required: true
#        default: '2.4.1'

env:
  JAVA_VERSION: 11.0.3
  SERVER_ID: ossrh
  PYTHON_VERSION: '3.9.7'
  MAVEN_VERSION: 3.8.1
  WINDOWS_VERSION: 'windows-2019'
  UBUNTU_VERSION: 'ubuntu-latest'
  MACOS_VERSION: 'macos-latest'



jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:


      - name: Create changelog config
        run: echo '{"max_back_track_time_days":1095}' > configuration.json

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## ğŸš€ Features",
                    "labels": ["feature"]
                },
                {
                    "title": "## ğŸ› Fixes",
                    "labels": ["fix"]
                },
                {
                    "title": "## ğŸ§ª Tests",
                    "labels": ["test"]
                },
                {
                    "title": "## ğŸ’¬ Other",
                    "labels": ["other"]
                },
                {
                    "title": "## ğŸ“¦ Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }
          toTag: Release/2.2.1
          fromTag: Manual-Release/2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: print change
        run: echo "${{ steps.changelog.outputs.changelog }}"

